import { createElement, type ReactElement } from 'react'
import {
  Activity,
  AlarmClock,
  Apple,
  Armchair,
  AtSign,
  Atom,
  Bandage,
  Beaker,
  Bed,
  BedDouble,
  Beef,
  Bell,
  Biohazard,
  Bird,
  Bone,
  Bookmark,
  Bot,
  Box,
  BrainCircuit,
  BriefcaseMedical,
  Bug,
  Calendar,
  Camera,
  Cat,
  CircleCheck,
  CirclePlay,
  ClipboardList,
  Clock,
  Cloud,
  CloudMoon,
  Code,
  Coffee,
  Cpu,
  CreditCard,
  Crown,
  Database,
  Dna,
  Dog,
  DollarSign,
  Download,
  Droplet,
  Droplets,
  Egg,
  Eye,
  FileCode2,
  FileText,
  Film,
  Filter,
  Fish,
  Flag,
  Flame,
  FlaskConical,
  FlaskRound,
  Flower2,
  Folder,
  Gamepad2,
  Gift,
  GitBranch,
  GitMerge,
  Globe,
  Goal,
  Hash,
  Heart,
  HeartPulse,
  Hospital,
  Hourglass,
  Image,
  Info,
  Key,
  Laugh,
  Layers,
  Leaf,
  Lightbulb,
  Link,
  Lock,
  Magnet,
  Mail,
  Map as MapIcon,
  MapPin,
  Medal,
  MessageSquare,
  Microscope,
  Moon,
  MoonStar,
  Music,
  Network,
  Orbit,
  Package,
  PartyPopper,
  Pause,
  PawPrint,
  Pill,
  Pipette,
  Power,
  Rabbit,
  Radiation,
  Repeat,
  Rocket,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  ShoppingCart,
  Shuffle,
  Sigma,
  Smile,
  Snowflake,
  Sparkles,
  Split,
  SportShoe,
  Star,
  Stethoscope,
  Sun,
  Sunrise,
  Sunset,
  Syringe,
  Table2,
  Tag,
  Terminal,
  TestTube,
  TestTubes,
  Thermometer,
  ThumbsUp,
  Timer,
  TreePine,
  TriangleAlert,
  Trophy,
  Truck,
  Turtle,
  Upload,
  User,
  Users,
  Volleyball,
  Waves,
  Webhook,
  Wheat,
  Wind,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

export interface IconGroup {
  label: string
  icons: { name: string; icon: LucideIcon }[]
}

/**
 * Icons a user can assign to any node, keyed by a stable name stored in node
 * data. Grouped for the picker; the original names live in the first groups so
 * existing flows keep their icons.
 */
export const ICON_GROUPS: IconGroup[] = [
  {
    label: 'Common',
    icons: [
      { name: 'workflow', icon: Workflow },
      { name: 'settings', icon: Settings },
      { name: 'file', icon: FileText },
      { name: 'clipboard', icon: ClipboardList },
      { name: 'search', icon: Search },
      { name: 'filter', icon: Filter },
      { name: 'flag', icon: Flag },
      { name: 'bell', icon: Bell },
      { name: 'calendar', icon: Calendar },
      { name: 'clock', icon: Clock },
      { name: 'timer', icon: Timer },
      { name: 'tag', icon: Tag },
      { name: 'bookmark', icon: Bookmark },
      { name: 'lightbulb', icon: Lightbulb },
      { name: 'info', icon: Info },
      { name: 'alert', icon: TriangleAlert },
    ],
  },
  {
    label: 'Flow & code',
    icons: [
      { name: 'code', icon: FileCode2 },
      { name: 'terminal', icon: Terminal },
      { name: 'code-tags', icon: Code },
      { name: 'branch', icon: GitBranch },
      { name: 'merge', icon: GitMerge },
      { name: 'split', icon: Split },
      { name: 'shuffle', icon: Shuffle },
      { name: 'repeat', icon: Repeat },
      { name: 'layers', icon: Layers },
      { name: 'network', icon: Network },
      { name: 'webhook', icon: Webhook },
      { name: 'wrench', icon: Wrench },
      { name: 'zap', icon: Zap },
      { name: 'cpu', icon: Cpu },
      { name: 'bot', icon: Bot },
      { name: 'brain', icon: BrainCircuit },
    ],
  },
  {
    label: 'Data & cloud',
    icons: [
      { name: 'database', icon: Database },
      { name: 'table', icon: Table2 },
      { name: 'globe', icon: Globe },
      { name: 'cloud', icon: Cloud },
      { name: 'server', icon: Server },
      { name: 'download', icon: Download },
      { name: 'upload', icon: Upload },
      { name: 'send', icon: Send },
      { name: 'mail', icon: Mail },
      { name: 'message', icon: MessageSquare },
      { name: 'link', icon: Link },
      { name: 'share', icon: Share2 },
      { name: 'image', icon: Image },
      { name: 'film', icon: Film },
      { name: 'music', icon: Music },
      { name: 'eye', icon: Eye },
    ],
  },
  {
    label: 'People & places',
    icons: [
      { name: 'user', icon: User },
      { name: 'users', icon: Users },
      { name: 'map', icon: MapIcon },
      { name: 'map-pin', icon: MapPin },
      { name: 'lock', icon: Lock },
      { name: 'key', icon: Key },
      { name: 'folder', icon: Folder },
      { name: 'camera', icon: Camera },
      { name: 'cart', icon: ShoppingCart },
      { name: 'card', icon: CreditCard },
      { name: 'dollar', icon: DollarSign },
      { name: 'hash', icon: Hash },
      { name: 'at', icon: AtSign },
      { name: 'truck', icon: Truck },
      { name: 'package', icon: Package },
      { name: 'box', icon: Box },
    ],
  },
  {
    label: 'Time & rest',
    icons: [
      { name: 'sleep', icon: BedDouble },
      { name: 'bed', icon: Bed },
      { name: 'moon', icon: Moon },
      { name: 'moon-star', icon: MoonStar },
      { name: 'cloud-moon', icon: CloudMoon },
      { name: 'alarm', icon: AlarmClock },
      { name: 'hourglass', icon: Hourglass },
      { name: 'pause', icon: Pause },
      { name: 'power', icon: Power },
      { name: 'armchair', icon: Armchair },
      { name: 'sunrise', icon: Sunrise },
      { name: 'sunset', icon: Sunset },
    ],
  },
  {
    label: 'Science & medical',
    icons: [
      { name: 'atom', icon: Atom },
      { name: 'dna', icon: Dna },
      { name: 'molecule', icon: Orbit },
      { name: 'flask', icon: FlaskConical },
      { name: 'flask-round', icon: FlaskRound },
      { name: 'beaker', icon: Beaker },
      { name: 'test-tube', icon: TestTube },
      { name: 'test-tubes', icon: TestTubes },
      { name: 'pipette', icon: Pipette },
      { name: 'microscope', icon: Microscope },
      { name: 'droplet', icon: Droplet },
      { name: 'droplets', icon: Droplets },
      { name: 'magnet', icon: Magnet },
      { name: 'sigma', icon: Sigma },
      { name: 'activity', icon: Activity },
      { name: 'heart-pulse', icon: HeartPulse },
      { name: 'thermometer', icon: Thermometer },
      { name: 'pill', icon: Pill },
      { name: 'syringe', icon: Syringe },
      { name: 'stethoscope', icon: Stethoscope },
      { name: 'bandage', icon: Bandage },
      { name: 'medical-bag', icon: BriefcaseMedical },
      { name: 'hospital', icon: Hospital },
      { name: 'bone', icon: Bone },
      { name: 'biohazard', icon: Biohazard },
      { name: 'radiation', icon: Radiation },
      { name: 'waves', icon: Waves },
      { name: 'wind', icon: Wind },
      { name: 'snowflake', icon: Snowflake },
      { name: 'apple', icon: Apple },
      { name: 'wheat', icon: Wheat },
      { name: 'egg', icon: Egg },
      { name: 'beef', icon: Beef },
    ],
  },
  {
    label: 'Nature & fun',
    icons: [
      { name: 'play', icon: CirclePlay },
      { name: 'check', icon: CircleCheck },
      { name: 'smile', icon: Smile },
      { name: 'laugh', icon: Laugh },
      { name: 'heart', icon: Heart },
      { name: 'thumbs-up', icon: ThumbsUp },
      { name: 'party', icon: PartyPopper },
      { name: 'sparkles', icon: Sparkles },
      { name: 'star', icon: Star },
      { name: 'trophy', icon: Trophy },
      { name: 'medal', icon: Medal },
      { name: 'crown', icon: Crown },
      { name: 'gift', icon: Gift },
      { name: 'rocket', icon: Rocket },
      { name: 'flame', icon: Flame },
      { name: 'gamepad', icon: Gamepad2 },
      { name: 'coffee', icon: Coffee },
      { name: 'sun', icon: Sun },
      { name: 'leaf', icon: Leaf },
      { name: 'tree', icon: TreePine },
      { name: 'flower', icon: Flower2 },
      { name: 'cat', icon: Cat },
      { name: 'dog', icon: Dog },
      { name: 'bird', icon: Bird },
      { name: 'rabbit', icon: Rabbit },
      { name: 'fish', icon: Fish },
      { name: 'turtle', icon: Turtle },
      { name: 'bug', icon: Bug },
      { name: 'paw', icon: PawPrint },
    ],
  },
  {
    label: 'Sports',
    icons: [
      { name: 'ball', icon: Volleyball },
      { name: 'goal', icon: Goal },
      { name: 'boot', icon: SportShoe },
    ],
  },
]

/** Flat list of every choice (kept for any callers that want all icons). */
export const ICON_CHOICES = ICON_GROUPS.flatMap((group) => group.icons)

const byName = new Map(ICON_CHOICES.map((choice) => [choice.name, choice.icon]))

export function getIconByName(name: string | undefined): LucideIcon | undefined {
  return name ? byName.get(name) : undefined
}

/** A node's icon: the user override when set and known, otherwise the default. */
export function resolveNodeIcon(override: string | undefined, fallback: LucideIcon): LucideIcon {
  return getIconByName(override) ?? fallback
}

/** Renders a registry icon (with optional fallback) without creating components in render. */
export function NodeIcon({
  name,
  fallback,
  className,
}: {
  name?: string
  fallback?: LucideIcon
  className?: string
}): ReactElement | null {
  const icon = getIconByName(name) ?? fallback
  return icon ? createElement(icon, { className }) : null
}
