import type { WorkflowDoc } from '@/types/workflow'

/**
 * Tour 5 — a real-world showcase: the 2026 FIFA World Cup knockout bracket
 * built from score-card nodes (one card per match: venue header, flag/name/
 * score rows, winner bold, loser greyed). Mirrored 16-left/16-right layout
 * converging on a gold Final card with trophy, plus a 3rd-place match.
 * Real results through the quarter-finals (per Wikipedia, as of Jul 12 2026);
 * semi-finals onward are the real upcoming fixtures with dates as tags.
 * Regenerated by scripts/generate-worldcup-template.py; match data is also
 * editable per-node in the inspector's Behavior tab.
 */
export const worldCup: WorkflowDoc = {
  "schemaVersion": 1,
  "settings": {
    "name": "Tour 5 · FIFA World Cup 2026",
    "version": "1.3.0",
    "description": "Mirrored 32-team knockout bracket built from score-card nodes: venue header, flag/name/score rows, winner in bold, gold final with trophy and a 3rd-place match. Real results through the quarter-finals; semi-finals onward are upcoming fixtures."
  },
  "flows": {
    "root": {
      "settings": {
        "direction": "lr"
      },
      "nodes": [
        {
          "id": "m1",
          "type": "scorecard",
          "position": {
            "x": 0,
            "y": 0
          },
          "data": {
            "label": "R32 · South Africa v Canada",
            "nodeType": "scorecard",
            "params": {
              "header": "Los Angeles",
              "tag": "Full time",
              "rows": [
                {
                  "icon": "🇿🇦",
                  "label": "South Africa",
                  "value": "0"
                },
                {
                  "icon": "🇨🇦",
                  "label": "Canada",
                  "value": "1",
                  "bold": true
                }
              ]
            }
          }
        },
        {
          "id": "m2",
          "type": "scorecard",
          "position": {
            "x": 0,
            "y": 140
          },
          "data": {
            "label": "R32 · Netherlands v Morocco",
            "nodeType": "scorecard",
            "params": {
              "header": "Monterrey",
              "tag": "Penalties",
              "rows": [
                {
                  "icon": "🇳🇱",
                  "label": "Netherlands",
                  "value": "1 (2)"
                },
                {
                  "icon": "🇲🇦",
                  "label": "Morocco",
                  "value": "1 (3)",
                  "bold": true
                }
              ]
            }
          }
        },
        {
          "id": "m3",
          "type": "scorecard",
          "position": {
            "x": 0,
            "y": 280
          },
          "data": {
            "label": "R32 · Germany v Paraguay",
            "nodeType": "scorecard",
            "params": {
              "header": "Boston",
              "tag": "Penalties",
              "rows": [
                {
                  "icon": "🇩🇪",
                  "label": "Germany",
                  "value": "1 (3)"
                },
                {
                  "icon": "🇵🇾",
                  "label": "Paraguay",
                  "value": "1 (4)",
                  "bold": true
                }
              ]
            }
          }
        },
        {
          "id": "m4",
          "type": "scorecard",
          "position": {
            "x": 0,
            "y": 420
          },
          "data": {
            "label": "R32 · France v Sweden",
            "nodeType": "scorecard",
            "params": {
              "header": "New York",
              "tag": "Full time",
              "rows": [
                {
                  "icon": "🇫🇷",
                  "label": "France",
                  "value": "3",
                  "bold": true
                },
                {
                  "icon": "🇸🇪",
                  "label": "Sweden",
                  "value": "0"
                }
              ]
            }
          }
        },
        {
          "id": "m5",
          "type": "scorecard",
          "position": {
            "x": 0,
            "y": 560
          },
          "data": {
            "label": "R32 · Portugal v Croatia",
            "nodeType": "scorecard",
            "params": {
              "header": "Toronto",
              "tag": "Full time",
              "rows": [
                {
                  "icon": "🇵🇹",
                  "label": "Portugal",
                  "value": "2",
                  "bold": true
                },
                {
                  "icon": "🇭🇷",
                  "label": "Croatia",
                  "value": "1"
                }
              ]
            }
          }
        },
        {
          "id": "m6",
          "type": "scorecard",
          "position": {
            "x": 0,
            "y": 700
          },
          "data": {
            "label": "R32 · Spain v Austria",
            "nodeType": "scorecard",
            "params": {
              "header": "Los Angeles",
              "tag": "Full time",
              "rows": [
                {
                  "icon": "🇪🇸",
                  "label": "Spain",
                  "value": "3",
                  "bold": true
                },
                {
                  "icon": "🇦🇹",
                  "label": "Austria",
                  "value": "0"
                }
              ]
            }
          }
        },
        {
          "id": "m7",
          "type": "scorecard",
          "position": {
            "x": 0,
            "y": 840
          },
          "data": {
            "label": "R32 · United States v Bosnia & Herz.",
            "nodeType": "scorecard",
            "params": {
              "header": "San Francisco",
              "tag": "Full time",
              "rows": [
                {
                  "icon": "🇺🇸",
                  "label": "United States",
                  "value": "2",
                  "bold": true
                },
                {
                  "icon": "🇧🇦",
                  "label": "Bosnia & Herz.",
                  "value": "0"
                }
              ]
            }
          }
        },
        {
          "id": "m8",
          "type": "scorecard",
          "position": {
            "x": 0,
            "y": 980
          },
          "data": {
            "label": "R32 · Belgium v Senegal",
            "nodeType": "scorecard",
            "params": {
              "header": "Seattle",
              "tag": "Extra time",
              "rows": [
                {
                  "icon": "🇧🇪",
                  "label": "Belgium",
                  "value": "3",
                  "bold": true
                },
                {
                  "icon": "🇸🇳",
                  "label": "Senegal",
                  "value": "2"
                }
              ]
            }
          }
        },
        {
          "id": "m9",
          "type": "scorecard",
          "position": {
            "x": 3800,
            "y": 0
          },
          "data": {
            "label": "R32 · Brazil v Japan",
            "nodeType": "scorecard",
            "params": {
              "header": "Houston",
              "tag": "Full time",
              "rows": [
                {
                  "icon": "🇧🇷",
                  "label": "Brazil",
                  "value": "2",
                  "bold": true
                },
                {
                  "icon": "🇯🇵",
                  "label": "Japan",
                  "value": "1"
                }
              ]
            }
          }
        },
        {
          "id": "m10",
          "type": "scorecard",
          "position": {
            "x": 3800,
            "y": 140
          },
          "data": {
            "label": "R32 · Ivory Coast v Norway",
            "nodeType": "scorecard",
            "params": {
              "header": "Dallas",
              "tag": "Full time",
              "rows": [
                {
                  "icon": "🇨🇮",
                  "label": "Ivory Coast",
                  "value": "1"
                },
                {
                  "icon": "🇳🇴",
                  "label": "Norway",
                  "value": "2",
                  "bold": true
                }
              ]
            }
          }
        },
        {
          "id": "m11",
          "type": "scorecard",
          "position": {
            "x": 3800,
            "y": 280
          },
          "data": {
            "label": "R32 · Mexico v Ecuador",
            "nodeType": "scorecard",
            "params": {
              "header": "Mexico City",
              "tag": "Full time",
              "rows": [
                {
                  "icon": "🇲🇽",
                  "label": "Mexico",
                  "value": "2",
                  "bold": true
                },
                {
                  "icon": "🇪🇨",
                  "label": "Ecuador",
                  "value": "0"
                }
              ]
            }
          }
        },
        {
          "id": "m12",
          "type": "scorecard",
          "position": {
            "x": 3800,
            "y": 420
          },
          "data": {
            "label": "R32 · England v DR Congo",
            "nodeType": "scorecard",
            "params": {
              "header": "Atlanta",
              "tag": "Full time",
              "rows": [
                {
                  "icon": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
                  "label": "England",
                  "value": "2",
                  "bold": true
                },
                {
                  "icon": "🇨🇩",
                  "label": "DR Congo",
                  "value": "1"
                }
              ]
            }
          }
        },
        {
          "id": "m13",
          "type": "scorecard",
          "position": {
            "x": 3800,
            "y": 560
          },
          "data": {
            "label": "R32 · Argentina v Cape Verde",
            "nodeType": "scorecard",
            "params": {
              "header": "Miami",
              "tag": "Extra time",
              "rows": [
                {
                  "icon": "🇦🇷",
                  "label": "Argentina",
                  "value": "3",
                  "bold": true
                },
                {
                  "icon": "🇨🇻",
                  "label": "Cape Verde",
                  "value": "2"
                }
              ]
            }
          }
        },
        {
          "id": "m14",
          "type": "scorecard",
          "position": {
            "x": 3800,
            "y": 700
          },
          "data": {
            "label": "R32 · Australia v Egypt",
            "nodeType": "scorecard",
            "params": {
              "header": "Dallas",
              "tag": "Penalties",
              "rows": [
                {
                  "icon": "🇦🇺",
                  "label": "Australia",
                  "value": "1 (2)"
                },
                {
                  "icon": "🇪🇬",
                  "label": "Egypt",
                  "value": "1 (4)",
                  "bold": true
                }
              ]
            }
          }
        },
        {
          "id": "m15",
          "type": "scorecard",
          "position": {
            "x": 3800,
            "y": 840
          },
          "data": {
            "label": "R32 · Switzerland v Algeria",
            "nodeType": "scorecard",
            "params": {
              "header": "Vancouver",
              "tag": "Full time",
              "rows": [
                {
                  "icon": "🇨🇭",
                  "label": "Switzerland",
                  "value": "2",
                  "bold": true
                },
                {
                  "icon": "🇩🇿",
                  "label": "Algeria",
                  "value": "0"
                }
              ]
            }
          }
        },
        {
          "id": "m16",
          "type": "scorecard",
          "position": {
            "x": 3800,
            "y": 980
          },
          "data": {
            "label": "R32 · Colombia v Ghana",
            "nodeType": "scorecard",
            "params": {
              "header": "Kansas City",
              "tag": "Full time",
              "rows": [
                {
                  "icon": "🇨🇴",
                  "label": "Colombia",
                  "value": "1",
                  "bold": true
                },
                {
                  "icon": "🇬🇭",
                  "label": "Ghana",
                  "value": "0"
                }
              ]
            }
          }
        },
        {
          "id": "r16_l1",
          "type": "scorecard",
          "position": {
            "x": 380,
            "y": 70
          },
          "data": {
            "label": "R16 · Canada v Morocco",
            "nodeType": "scorecard",
            "params": {
              "header": "Houston",
              "tag": "Full time",
              "rows": [
                {
                  "icon": "🇨🇦",
                  "label": "Canada",
                  "value": "0"
                },
                {
                  "icon": "🇲🇦",
                  "label": "Morocco",
                  "value": "3",
                  "bold": true
                }
              ]
            }
          }
        },
        {
          "id": "r16_l2",
          "type": "scorecard",
          "position": {
            "x": 380,
            "y": 350
          },
          "data": {
            "label": "R16 · Paraguay v France",
            "nodeType": "scorecard",
            "params": {
              "header": "Philadelphia",
              "tag": "Full time",
              "rows": [
                {
                  "icon": "🇵🇾",
                  "label": "Paraguay",
                  "value": "0"
                },
                {
                  "icon": "🇫🇷",
                  "label": "France",
                  "value": "1",
                  "bold": true
                }
              ]
            }
          }
        },
        {
          "id": "r16_l3",
          "type": "scorecard",
          "position": {
            "x": 380,
            "y": 630
          },
          "data": {
            "label": "R16 · Portugal v Spain",
            "nodeType": "scorecard",
            "params": {
              "header": "Dallas",
              "tag": "Full time",
              "rows": [
                {
                  "icon": "🇵🇹",
                  "label": "Portugal",
                  "value": "0"
                },
                {
                  "icon": "🇪🇸",
                  "label": "Spain",
                  "value": "1",
                  "bold": true
                }
              ]
            }
          }
        },
        {
          "id": "r16_l4",
          "type": "scorecard",
          "position": {
            "x": 380,
            "y": 910
          },
          "data": {
            "label": "R16 · United States v Belgium",
            "nodeType": "scorecard",
            "params": {
              "header": "Seattle",
              "tag": "Full time",
              "rows": [
                {
                  "icon": "🇺🇸",
                  "label": "United States",
                  "value": "1"
                },
                {
                  "icon": "🇧🇪",
                  "label": "Belgium",
                  "value": "4",
                  "bold": true
                }
              ]
            }
          }
        },
        {
          "id": "r16_r1",
          "type": "scorecard",
          "position": {
            "x": 3420,
            "y": 70
          },
          "data": {
            "label": "R16 · Brazil v Norway",
            "nodeType": "scorecard",
            "params": {
              "header": "New York",
              "tag": "Full time",
              "rows": [
                {
                  "icon": "🇧🇷",
                  "label": "Brazil",
                  "value": "1"
                },
                {
                  "icon": "🇳🇴",
                  "label": "Norway",
                  "value": "2",
                  "bold": true
                }
              ]
            }
          }
        },
        {
          "id": "r16_r2",
          "type": "scorecard",
          "position": {
            "x": 3420,
            "y": 350
          },
          "data": {
            "label": "R16 · Mexico v England",
            "nodeType": "scorecard",
            "params": {
              "header": "Mexico City",
              "tag": "Full time",
              "rows": [
                {
                  "icon": "🇲🇽",
                  "label": "Mexico",
                  "value": "2"
                },
                {
                  "icon": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
                  "label": "England",
                  "value": "3",
                  "bold": true
                }
              ]
            }
          }
        },
        {
          "id": "r16_r3",
          "type": "scorecard",
          "position": {
            "x": 3420,
            "y": 630
          },
          "data": {
            "label": "R16 · Argentina v Egypt",
            "nodeType": "scorecard",
            "params": {
              "header": "Atlanta",
              "tag": "Full time",
              "rows": [
                {
                  "icon": "🇦🇷",
                  "label": "Argentina",
                  "value": "3",
                  "bold": true
                },
                {
                  "icon": "🇪🇬",
                  "label": "Egypt",
                  "value": "2"
                }
              ]
            }
          }
        },
        {
          "id": "r16_r4",
          "type": "scorecard",
          "position": {
            "x": 3420,
            "y": 910
          },
          "data": {
            "label": "R16 · Switzerland v Colombia",
            "nodeType": "scorecard",
            "params": {
              "header": "Vancouver",
              "tag": "Penalties",
              "rows": [
                {
                  "icon": "🇨🇭",
                  "label": "Switzerland",
                  "value": "0 (4)",
                  "bold": true
                },
                {
                  "icon": "🇨🇴",
                  "label": "Colombia",
                  "value": "0 (3)"
                }
              ]
            }
          }
        },
        {
          "id": "qf_l1",
          "type": "scorecard",
          "position": {
            "x": 760,
            "y": 210
          },
          "data": {
            "label": "QF · France v Morocco",
            "nodeType": "scorecard",
            "params": {
              "header": "Boston",
              "tag": "Full time",
              "rows": [
                {
                  "icon": "🇫🇷",
                  "label": "France",
                  "value": "2",
                  "bold": true
                },
                {
                  "icon": "🇲🇦",
                  "label": "Morocco",
                  "value": "0"
                }
              ]
            }
          }
        },
        {
          "id": "qf_l2",
          "type": "scorecard",
          "position": {
            "x": 760,
            "y": 770
          },
          "data": {
            "label": "QF · Spain v Belgium",
            "nodeType": "scorecard",
            "params": {
              "header": "Los Angeles",
              "tag": "Full time",
              "rows": [
                {
                  "icon": "🇪🇸",
                  "label": "Spain",
                  "value": "2",
                  "bold": true
                },
                {
                  "icon": "🇧🇪",
                  "label": "Belgium",
                  "value": "1"
                }
              ]
            }
          }
        },
        {
          "id": "qf_r1",
          "type": "scorecard",
          "position": {
            "x": 3040,
            "y": 210
          },
          "data": {
            "label": "QF · Norway v England",
            "nodeType": "scorecard",
            "params": {
              "header": "Miami",
              "tag": "Extra time",
              "rows": [
                {
                  "icon": "🇳🇴",
                  "label": "Norway",
                  "value": "1"
                },
                {
                  "icon": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
                  "label": "England",
                  "value": "2",
                  "bold": true
                }
              ]
            }
          }
        },
        {
          "id": "qf_r2",
          "type": "scorecard",
          "position": {
            "x": 3040,
            "y": 770
          },
          "data": {
            "label": "QF · Argentina v Switzerland",
            "nodeType": "scorecard",
            "params": {
              "header": "Kansas City",
              "tag": "Extra time",
              "rows": [
                {
                  "icon": "🇦🇷",
                  "label": "Argentina",
                  "value": "3",
                  "bold": true
                },
                {
                  "icon": "🇨🇭",
                  "label": "Switzerland",
                  "value": "1"
                }
              ]
            }
          }
        },
        {
          "id": "sf_l",
          "type": "scorecard",
          "position": {
            "x": 1140,
            "y": 490
          },
          "data": {
            "label": "SF · France v Spain",
            "nodeType": "scorecard",
            "params": {
              "header": "Dallas",
              "tag": "Jul 14",
              "rows": [
                {
                  "icon": "🇫🇷",
                  "label": "France"
                },
                {
                  "icon": "🇪🇸",
                  "label": "Spain"
                }
              ]
            }
          }
        },
        {
          "id": "sf_r",
          "type": "scorecard",
          "position": {
            "x": 2660,
            "y": 490
          },
          "data": {
            "label": "SF · England v Argentina",
            "nodeType": "scorecard",
            "params": {
              "header": "Atlanta",
              "tag": "Jul 15",
              "rows": [
                {
                  "icon": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
                  "label": "England"
                },
                {
                  "icon": "🇦🇷",
                  "label": "Argentina"
                }
              ]
            }
          }
        },
        {
          "id": "final",
          "type": "scorecard",
          "position": {
            "x": 1900,
            "y": 450
          },
          "data": {
            "label": "Final · New York",
            "nodeType": "scorecard",
            "params": {
              "header": "New York",
              "tag": "Jul 19",
              "rows": [
                {
                  "label": "🇫🇷 🇪🇸 winner"
                },
                {
                  "label": "🏴󠁧󠁢󠁥󠁮󠁧󠁿 🇦🇷 winner"
                }
              ],
              "emblem": "🏆",
              "accent": true
            }
          }
        },
        {
          "id": "third",
          "type": "scorecard",
          "position": {
            "x": 1900,
            "y": 700
          },
          "data": {
            "label": "3rd place · Miami",
            "nodeType": "scorecard",
            "params": {
              "header": "Miami",
              "tag": "Jul 18",
              "rows": [
                {
                  "label": "🇫🇷 🇪🇸 loser"
                },
                {
                  "label": "🏴󠁧󠁢󠁥󠁮󠁧󠁿 🇦🇷 loser"
                }
              ],
              "caption": "3RD-PLACE"
            }
          }
        },
        {
          "id": "note_r32_l",
          "type": "note",
          "position": {
            "x": 0,
            "y": -150
          },
          "data": {
            "label": "Round of 32",
            "nodeType": "note",
            "params": {
              "text": "Round of 32"
            }
          }
        },
        {
          "id": "note_r16_l",
          "type": "note",
          "position": {
            "x": 380,
            "y": -150
          },
          "data": {
            "label": "Round of 16",
            "nodeType": "note",
            "params": {
              "text": "Round of 16"
            }
          }
        },
        {
          "id": "note_qf_l",
          "type": "note",
          "position": {
            "x": 760,
            "y": -150
          },
          "data": {
            "label": "Quarter-finals",
            "nodeType": "note",
            "params": {
              "text": "Quarter-finals"
            }
          }
        },
        {
          "id": "note_sf_l",
          "type": "note",
          "position": {
            "x": 1140,
            "y": -150
          },
          "data": {
            "label": "Semi-finals",
            "nodeType": "note",
            "params": {
              "text": "Semi-finals"
            }
          }
        },
        {
          "id": "note_final",
          "type": "note",
          "position": {
            "x": 1900,
            "y": -150
          },
          "data": {
            "label": "Final",
            "nodeType": "note",
            "params": {
              "text": "Final"
            }
          }
        },
        {
          "id": "note_sf_r",
          "type": "note",
          "position": {
            "x": 2660,
            "y": -150
          },
          "data": {
            "label": "Semi-finals",
            "nodeType": "note",
            "params": {
              "text": "Semi-finals"
            }
          }
        },
        {
          "id": "note_qf_r",
          "type": "note",
          "position": {
            "x": 3040,
            "y": -150
          },
          "data": {
            "label": "Quarter-finals",
            "nodeType": "note",
            "params": {
              "text": "Quarter-finals"
            }
          }
        },
        {
          "id": "note_r16_r",
          "type": "note",
          "position": {
            "x": 3420,
            "y": -150
          },
          "data": {
            "label": "Round of 16",
            "nodeType": "note",
            "params": {
              "text": "Round of 16"
            }
          }
        },
        {
          "id": "note_r32_r",
          "type": "note",
          "position": {
            "x": 3800,
            "y": -150
          },
          "data": {
            "label": "Round of 32",
            "nodeType": "note",
            "params": {
              "text": "Round of 32"
            }
          }
        }
      ],
      "edges": [
        {
          "id": "e_m1_r16_l1",
          "source": "m1",
          "target": "r16_l1",
          "sourceHandle": "right",
          "targetHandle": "left"
        },
        {
          "id": "e_m2_r16_l1",
          "source": "m2",
          "target": "r16_l1",
          "sourceHandle": "right",
          "targetHandle": "left"
        },
        {
          "id": "e_m3_r16_l2",
          "source": "m3",
          "target": "r16_l2",
          "sourceHandle": "right",
          "targetHandle": "left"
        },
        {
          "id": "e_m4_r16_l2",
          "source": "m4",
          "target": "r16_l2",
          "sourceHandle": "right",
          "targetHandle": "left"
        },
        {
          "id": "e_m5_r16_l3",
          "source": "m5",
          "target": "r16_l3",
          "sourceHandle": "right",
          "targetHandle": "left"
        },
        {
          "id": "e_m6_r16_l3",
          "source": "m6",
          "target": "r16_l3",
          "sourceHandle": "right",
          "targetHandle": "left"
        },
        {
          "id": "e_m7_r16_l4",
          "source": "m7",
          "target": "r16_l4",
          "sourceHandle": "right",
          "targetHandle": "left"
        },
        {
          "id": "e_m8_r16_l4",
          "source": "m8",
          "target": "r16_l4",
          "sourceHandle": "right",
          "targetHandle": "left"
        },
        {
          "id": "e_r16_l1_qf_l1",
          "source": "r16_l1",
          "target": "qf_l1",
          "sourceHandle": "right",
          "targetHandle": "left"
        },
        {
          "id": "e_r16_l2_qf_l1",
          "source": "r16_l2",
          "target": "qf_l1",
          "sourceHandle": "right",
          "targetHandle": "left"
        },
        {
          "id": "e_r16_l3_qf_l2",
          "source": "r16_l3",
          "target": "qf_l2",
          "sourceHandle": "right",
          "targetHandle": "left"
        },
        {
          "id": "e_r16_l4_qf_l2",
          "source": "r16_l4",
          "target": "qf_l2",
          "sourceHandle": "right",
          "targetHandle": "left"
        },
        {
          "id": "e_qf_l1_sf_l",
          "source": "qf_l1",
          "target": "sf_l",
          "sourceHandle": "right",
          "targetHandle": "left"
        },
        {
          "id": "e_qf_l2_sf_l",
          "source": "qf_l2",
          "target": "sf_l",
          "sourceHandle": "right",
          "targetHandle": "left"
        },
        {
          "id": "e_m9_r16_r1",
          "source": "m9",
          "target": "r16_r1",
          "sourceHandle": "left",
          "targetHandle": "right"
        },
        {
          "id": "e_m10_r16_r1",
          "source": "m10",
          "target": "r16_r1",
          "sourceHandle": "left",
          "targetHandle": "right"
        },
        {
          "id": "e_m11_r16_r2",
          "source": "m11",
          "target": "r16_r2",
          "sourceHandle": "left",
          "targetHandle": "right"
        },
        {
          "id": "e_m12_r16_r2",
          "source": "m12",
          "target": "r16_r2",
          "sourceHandle": "left",
          "targetHandle": "right"
        },
        {
          "id": "e_m13_r16_r3",
          "source": "m13",
          "target": "r16_r3",
          "sourceHandle": "left",
          "targetHandle": "right"
        },
        {
          "id": "e_m14_r16_r3",
          "source": "m14",
          "target": "r16_r3",
          "sourceHandle": "left",
          "targetHandle": "right"
        },
        {
          "id": "e_m15_r16_r4",
          "source": "m15",
          "target": "r16_r4",
          "sourceHandle": "left",
          "targetHandle": "right"
        },
        {
          "id": "e_m16_r16_r4",
          "source": "m16",
          "target": "r16_r4",
          "sourceHandle": "left",
          "targetHandle": "right"
        },
        {
          "id": "e_r16_r1_qf_r1",
          "source": "r16_r1",
          "target": "qf_r1",
          "sourceHandle": "left",
          "targetHandle": "right"
        },
        {
          "id": "e_r16_r2_qf_r1",
          "source": "r16_r2",
          "target": "qf_r1",
          "sourceHandle": "left",
          "targetHandle": "right"
        },
        {
          "id": "e_r16_r3_qf_r2",
          "source": "r16_r3",
          "target": "qf_r2",
          "sourceHandle": "left",
          "targetHandle": "right"
        },
        {
          "id": "e_r16_r4_qf_r2",
          "source": "r16_r4",
          "target": "qf_r2",
          "sourceHandle": "left",
          "targetHandle": "right"
        },
        {
          "id": "e_qf_r1_sf_r",
          "source": "qf_r1",
          "target": "sf_r",
          "sourceHandle": "left",
          "targetHandle": "right"
        },
        {
          "id": "e_qf_r2_sf_r",
          "source": "qf_r2",
          "target": "sf_r",
          "sourceHandle": "left",
          "targetHandle": "right"
        },
        {
          "id": "e_sf_l_final",
          "source": "sf_l",
          "target": "final",
          "sourceHandle": "right",
          "targetHandle": "left"
        },
        {
          "id": "e_sf_r_final",
          "source": "sf_r",
          "target": "final",
          "sourceHandle": "left",
          "targetHandle": "right"
        },
        {
          "id": "e_sf_l_third",
          "source": "sf_l",
          "target": "third",
          "sourceHandle": "right",
          "targetHandle": "left"
        },
        {
          "id": "e_sf_r_third",
          "source": "sf_r",
          "target": "third",
          "sourceHandle": "left",
          "targetHandle": "right"
        }
      ]
    }
  }
}
